# Generated by Django 5.2.17 on 2026-09-01 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factures', '0002_facture_date_dernier_rappel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneReleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, help_text='Positif si crédit (argent reçu), négatif si débit', max_digits=10)),
                ('communication', models.CharField(blank=True, max_length=255)),
                ('rapprochee', models.BooleanField(default=False)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_releve', to='factures.facture')),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
    ]
