# Generated by Django 5.2.17 on 2026-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('fournitures', 'Fournitures de bureau'), ('deplacement', 'Déplacement'), ('logiciel', 'Logiciel / Abonnement'), ('marketing', 'Marketing'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=21.0, max_digits=5)),
                ('date_depense', models.DateField()),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
