# Generated by Django 5.2.17 on 2026-09-04 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='commentaire_comptable',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depense',
            name='statut_validation',
            field=models.CharField(choices=[('a_valider', 'À valider'), ('validee', 'Validée'), ('a_corriger', 'À corriger')], default='a_valider', max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
