# Generated by Django 5.2.17 on 2026-09-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_dernier_rappel',
            field=models.DateField(blank=True, help_text='Date du dernier rappel de paiement envoyé', null=True),
        ),
    ]
