# Generated by Django 5.2.17 on 2026-09-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depenses', '0001_initial'),
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: 700, 440, 411', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_compte', models.CharField(choices=[('actif', 'Actif'), ('passif', 'Passif'), ('charge', 'Charge'), ('produit', 'Produit')], max_length=20)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ecriture', models.DateField()),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_credit', to='comptabilite.comptecomptable')),
                ('compte_debit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures_debit', to='comptabilite.comptecomptable')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='depenses.depense')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='factures.facture')),
            ],
            options={
                'ordering': ['-date_ecriture'],
            },
        ),
    ]
