# Generated by Django 5.2.17 on 2026-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
    ]
